name: Build Images

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to build images for
        required: true
        type: environment
        default: development

jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'Done building images!'
